apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv              # pv 名稱
  labels:
    app: kubernetesdemo-jenkins
spec:
  capacity:
    storage: 10Gi               # 指定大小
  # volumeMode field requires BlockVolume Alpha feature gate to be enabled.
  volumeMode: Filesystem
  # accessModes =>
  # ReadWriteOnce 被單一Node掛載為 read/write 模式
  # ReadOnlyMany 被多個Node掛載為 read 模式
  # ReadWriteMany 被多個Node掛載為 read/write 模式
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  # 綁定在 host 的 tmp 資料夾
  hostPath:
    path: /home/meow/volume/jenkins
#  local:
#    path: /home/meow/jenkins/volume
#  nodeAffinity:
#    required:
#      nodeSelectorTerms:
#        - matchExpressions:
#            - key: kubernetes.io/hostname
#              operator: In
#              values:
#                - minikube
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  labels:
    app: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  # storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi #1 GB